### ISSUE TITLE
Dependency on old Rlang package

### ISSUE THREAD

**Issue by daenuthelawyer** [evan-l-munson/saotd#12]
When I follow your instructions on https://cran.r-project.org/web/packages/saotd/vignettes/saotd.html under the Aquire section, R comes up with an error:

Error in mutate_impl(.data, dots) : 
  Evaluation error: `as_dictionary()` is defunct as of rlang 0.3.0.
Please use `as_data_pronoun()` instead

Unfortunately, I don't have the opportunity to test if this error occurs on other systems and r installations. The error message, however, indicates an old dependency, which should be updated. I hope somebody can fix this.

**Comment by evan-l-munson** [comment]
Interesting, I will take a look and see if I can re-create your error message.

**Comment by evan-l-munson** [comment]
I just reloaded `saotd` into a new project and was able to run the acquire function without any issues using the following code:

`
library(saotd)

consumer_key <- xxxxxxxxxxxxxxxxx
consumer_secret <- xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
access_token <- xxxxxxxxxxxxxxxxx-xxxxxxxxxxxxxxxxx
access_secret <- xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

saotd::tweet_acquire(consumer_key = consumer_key, 
                     consumer_secret = consumer_secret, 
                     access_token = access_token, 
                     access_secret = access_secret, 
                     HT = c("#job", "#4runner"), 
                     num_tweets = 100, 
                     file_name = "rlang_test.rda", 
                     distinct = TRUE)

load("rlang_test.rda")`

**Comment by daenuthelawyer** [comment]
Thank you very much for your quick answer. I went through the aquire function and discovered that my dplyr installation was not up to date. Sorry for the disturbance.

**Comment by evan-l-munson** [comment]
No worries
