### ISSUE TITLE
saotd not installing on r

### ISSUE THREAD

**Issue by omnep1** [evan-l-munson/saotd#13]
E> * preparing 'saotd':
E> * checking DESCRIPTION meta-information ... OK
E> Error in loadVignetteBuilder(pkgdir, TRUE) : 
E>   vignette builder 'knitr' not found
E> Execution halted

**Comment by evan-l-munson** [comment]
@omnep1, appreciate the note.  When `dplyr` was updated 1.0.0 it caused a number of breakages in the `saotd` package.  I have been preoccupied with work, but will be working to fix the package.

**Comment by evan-l-munson** [comment]
@omnep1, the `saotd` package has been updated.  It should now be avaliable via:

- `install.packages("saotd")`
- `devtools::install_github('evan-l-munson/saotd', build_vignettes = TRUE)`
